import React from 'react'
import Footer from '../comps/footer'
import Navbar from '../comps/navbar'
import styles from '../styles/faq.module.css'

import { UilHome } from '@iconscout/react-unicons'
import { Link } from 'react-router-dom'

function Terms() {
  return (
    <>
    <Navbar /> 
      <div className={styles.container}>
        <div className={styles.faqs}>
          <p>
          TERMS OF SALE<br />

          <br />PLEASE READ THESE TERMS OF SALE CAREFULLY BEFORE ORDERING PRODUCTS ONLINE FROM THE LATTER HOUSE PLATFORM. PLEASE, NOTE THAT THESE TERMS OF SALE INCLUDE THE ADDITIONAL TERMS INCORPORATED HEREIN BY REFERENCE.   PURCHASES MADE IN AUSTRALIA, CANADA, EGYPT, INDIA, INDONESIA, ISRAEL, MALAYSIA, MEXICO, MOROCCO, NEW ZEALAND, PHILIPPINES, PUERTO RICO, RUSSIA, SAUDI ARABIA, SINGAPORE, SOUTH AFRICA, TAIWAN, THAILAND, UNITED ARAB EMIRATES, AND VIETNAM ARE GOVERNED BY DIFFERENT TERMS.<br />

          <br />IF YOU ARE LOCATED IN ANY OF THE COUNTRIES IDENTIFIED BELOW, ADDITIONAL COUNTRY-SPECIFIC TERMS MAY APPLY TO YOU AND ARE VIEWABLE AT THE END OF THESE TERMS OF SALE OR BY CLICKING ON THE COUNTRY REFERENCE LINK. THESE ADDITIONAL TERMS OVERRIDE THE TERMS BELOW TO THE EXTENT OF ANY INCONSISTENCY.

          <br />CHINA, COSTA RICA, DOMINICAN REPUBLIC, KOREA.<br />

          <br />APPLICABILITY<br />

          <br />YOU ARE READING THESE TERMS OF SALE (“TERMS OF SALE”) BECAUSE YOU ARE USING A LATTER HOUSE WEBSITE, DIGITAL EXPERIENCE, SOCIAL MEDIA PLATFORM, MOBILE APP, WEARABLE TECHNOLOGY, OR ONE OF OUR OTHER PRODUCTS OR SERVICES, ALL OF WHICH ARE PART OF LATTER HOUSE’S PLATFORM (“PLATFORM”). THESE TERMS OF SALE CREATE A LEGALLY BINDING AGREEMENT BETWEEN YOU AND LATTER HOUSE AND ITS AFFILIATES (WHICH WE MAY REFER TO AS “LATTER HOUSE,” “WE,” “US,” OR “OUR”) REGARDING ORDERS PLACED FOR PRODUCTS AVAILABLE ON THE PLATFORM.  LATTER HOUSE MAY REVISE THESE TERMS OF SALE WITHOUT NOTICE BY POSTING REVISED TERMS OF SALE ON ITS PLATFORM.  THE TERMS OF SALE POSTED ON THE PLATFORM AT THE TIME YOU PLACE YOUR ORDER ON THE PLATFORM WILL GOVERN THAT PURCHASE.  PLEASE READ THESE TERMS CAREFULLY AND CHECK THAT THE DETAILS OF YOUR ORDER ARE COMPLETE AND ACCURATE BEFORE SUBMITTING YOUR ORDER. IF YOU THINK THAT THERE IS A MISTAKE, PLEASE CONTACT US: INFO@LATTER HOUSE.COM. LATTER HOUSE’S TERMS OF USE AND PRIVACY POLICY ARE INCORPORATED HEREIN BY THIS REFERENCE.<br />

          <br />PLACING ORDERS ON THE PLATFORM<br />

          <br />ELIGIBILITY TO ORDER<br />

          <br />TO PLACE AN ORDER ON THE PLATFORM, YOU MUST BE OF LEGAL AGE IN YOUR COUNTRY AND A CONSUMER.<br />

          <br />“PRODUCT(S)” SHALL MEAN ANY GOODS PURCHASED THROUGH THIS SITE, AND ANY SUBDOMAINS.<br />

          <br />LATTER HOUSE MAY CHANGE THE PRODUCT (I) TO REFLECT ANY CHANGES IN RELEVANT LAWS AND REGULATORY REQUIREMENTS AND (II) TO IMPLEMENT MINOR TECHNICAL ADJUSTMENTS AND IMPROVEMENTS. THESE CHANGES WILL NOT AFFECT THE CLIENT'S USE OF THE PRODUCT.<br />

          <br />ORDER PROCESS, PAYMENT, AND ELECTRONIC COMMUNICATIONS.<br />

          <br />IF YOU PLACE ANY ORDERS FOR PRODUCTS ON THE SITE, YOU ARE EXPRESSLY AGREEING THAT LATTER HOUSE IS PERMITTED TO BILL YOU THE APPLICABLE FEES, ANY APPLICABLE TAX AND ANY OTHER CHARGES YOU MAY INCUR WITH LATTER HOUSE YOU AGREE THAT THE FEES WILL BE BILLED TO YOUR PAYMENT CARD YOU PROVIDE IN ACCORDANCE WITH THE BILLING TERMS IN EFFECT AT THE TIME A FEE OR CHARGE IS DUE AND PAYABLE, AS APPLICABLE. ALL BILLING INFORMATION MUST MATCH THE SHIPPING ADDRESS, NO EXCEPTIONS. NO ORDERS, BILLING INFORMATION, OR PURCHASES MADE BY A CUSTOMER OUTSIDE THE UNITED STATES (AND IN THOSE INSTANCES IDENTIFIED IN THE PRODUCTS LISTING, THOSE EXCLUDED STATES WITHIN THE UNITED STATES) WILL BE ACCEPTED, OR PROCESSED. IF PAYMENT IS NOT RECEIVED OR CANNOT BE CHARGED TO YOUR PAYMENT CARD FOR ANY REASON IN ADVANCE OF SHIPPING YOUR ORDER, LATTER HOUSE RESERVES THE RIGHT TO EITHER SUSPEND OR TERMINATE YOUR ORDER.<br />

          <br />BY PLACING AN ORDER WITH US, YOU AUTHORIZE US OR OUR DESIGNEE TO FACILITATE SHIPMENT TO YOUR ADDRESS OUTSIDE CANADA AND THE UNITED STATES (IF APPLICABLE). YOU ALSO ACKNOWLEDGE THAT, PURSUANT TO THE CUSTOM LAWS OF THE REGION OF YOUR PLACE OF DELIVERY, ANY INTERNATIONAL SHIPENT MAY INCUR DUTIES AND IMPORT TAXES UPON DELIVERY. THIS CHARGE IS DETERMINED BY YOUR LOCAL CUSTOMS AUTHORITY. PAYMENT OF THESE CHARGES MAY BE NECESSARY TO RELEASE YOUR ORDER FROM CUSTOMS. FOR MORE INFORMATION, PLEASE CONSULT YOUR LOCAL CUSTOMS OFFICE.<br />

          <br />ALL ORDERS PLACED BY YOU ARE SUBJECT TO ACCEPTANCE BY LATTER HOUSE AND ALL ITEMS ARE SUBJECT TO AVAILABILITY. ORDER PROCESSING MAY TAKE BETWEEN 1 TO 7 DAYS (NOT INCLUDING WEEKENDS OR HOLIDAYS) AND SOMETIMES LONGER, DEPENDING UPON VOLUME OF ORDERS.  SPECIAL PRODUCT ORDERS (INCLUDING LIMITED EDITIONS, AND PRE-ORDER OFFERS) MAY CONTAIN ADDITIONAL TERMS, OF WHICH WILL BE PROVIDED FOR EACH RESPECTIVE PRODUCT.  PLEASE READ PRODUCT SALES TERMS LISTED FOR EACH PRODUCT CAREFULLY BEFORE PLACING YOUR ORDER.<br />

          <br />ACKNOWLEDGEMENT OF YOUR ORDER MEANS THAT LATTER HOUSE HAS RECEIVED YOUR ORDER REQUEST; IT DOES NOT MEAN THAT YOUR ORDER HAS BEEN ACCEPTED OR SHIPPED, OR THAT THE PRICE OR AVAILABILITY OF AN ITEM HAS BEEN CONFIRMED. LATTER HOUSE MAY IN ITS DISCRETION REQUIRE ADDITIONAL VERIFICATION OR INFORMATION BEFORE ACCEPTING ANY ORDER.<br />

          <br />LATTER HOUSE RESERVES THE RIGHT, WITHOUT PRIOR NOTICE AND IN ITS SOLE DISCRETION, TO REFUSE OR CANCEL ANY ORDER FOR ANY REASON. SOME SITUATIONS THAT MAY RESULT IN YOUR ORDER BEING CANCELED INCLUDE, BUT ARE NOT LIMITED TO: INVALID, INCOMPLETE, IMPROPER, OR MISSING PAYMENT OR SHIPPING INFORMATION; LIMITATIONS ON QUANTITIES AVAILABLE FOR PURCHASE; INACCURACIES OR ERRORS IN PRODUCT OR PRICING INFORMATION; USE OF ANY ROBOT, SPIDER OR OTHER AUTOMATIC DEVICE, SOFTWARE, PROCESS OR APPLICATION TO PLACE, OR TAKE PREPARATORY STEPS TO PLACE, ONE OR MORE ORDERS; VIOLATION OF THESE TERMS AND CONDITIONS; OR ACTUAL OR SUSPECTED FRAUD OR ABUSE.<br />

          <br />BY USING THE SITE, YOU CONSENT TO RECEIVING ELECTRONIC COMMUNICATIONS FROM LATTER HOUSE. THESE ELECTRONIC COMMUNICATIONS MAY INCLUDE NOTICES ABOUT APPLICABLE FEES AND CHARGES, TRANSACTIONAL INFORMATION AND OTHER INFORMATION CONCERNING OR RELATED TO OUR SITE AND SERVICES. THESE ELECTRONIC COMMUNICATIONS ARE PART OF YOUR RELATIONSHIP WITH LATTER HOUSE AND YOU RECEIVE THEM AS PART OF YOUR PRODUCT ORDER. YOU AGREE THAT ANY NOTICES, AGREEMENTS, DISCLOSURES OR OTHER COMMUNICATIONS THAT WE SEND YOU ELECTRONICALLY WILL SATISFY ANY LEGAL COMMUNICATION REQUIREMENTS, INCLUDING THAT SUCH COMMUNICATIONS BE IN WRITING.<br />

          <br />SHIPPING AND RETURNS/EXCHANGES. ANY ESTIMATED ARRIVAL OR DELIVERY DATE PROVIDED BY LATTER HOUSE IS NOT A GUARANTEE. ALTHOUGH LATTER HOUSE WILL MAKE REASONABLE EFFORT TO MEET ESTIMATED DATES, DELIVERY OF THE PRODUCT MAY TAKE MORE OR LESS TIME THAN ESTIMATED AND LATTER HOUSE DISCLAIMS ANY LOSS, DAMAGE, OR INJURY RESULTING FROM A DELAY IN ARRIVAL OR DELIVERY. IF LATTER HOUSE IS UNABLE TO DELIVER THE PRODUCTS WITHIN THIRTY (30) DAYS AFTER IT CONFIRMS ACCEPTANCE OF THE ORDER, IT WILL NOTIFY YOU ACCORDINGLY. IN SUCH EVENT, YOU HAVE THE RIGHT TO EITHER AGREE TO A NEW DELIVERY DATE OR TO CANCEL YOUR PURCHASE WITHOUT INCURRING ANY COSTS, AND YOU WILL RECEIVE A REFUND FOR ANY PRODUCTS PAID FOR BUT NOT RECEIVED.  YOU ACKNOWLEDGE AND AGREE THAT LATTER HOUSE SHALL NOT BE LIABLE FOR, OR OTHERWISE OBLIGATED TO APPROVE OR ACCEPT ANY CANCELLATIONS OR REFUNDS REQUESTS FROM YOU RELATED TO ANY: (I) PRE-ORDER PRODUCTS; (II) LIMITED EDITION PRODUCTS; (III) FINAL SALE PRODUCTS; (IV) CUSTOM ORDER PRODUCTS; (V) PRODUCTS THAT HAVE PRODUCED AND/OR SHIPPED PRIOR TO SUCH CANCELLATION AND/OR REFUND REQUEST; AND (VI) THOSE PRODUCTS SUBJECT TO ADDITIONAL TERMS AND CONDITIONS IDENTIFIED IN THEIR RESPECTIVE PRODUCTS LISTING.<br />

          <br />IF THE ORDERED PRODUCT IS OUT OF STOCK OR CAN NO LONGER BE SUPPLIED FOR ANY OTHER REASON, LATTER HOUSE MAY ELECT TO CANCEL THE ORDER BY NOTIFYING YOU IN WRITING, AND REFUND YOUR PURCHASE.<br />

          <br />LATTER HOUSE DOES NOT AUTHORIZE THE SALE OF PRODUCTS BY UNAUTHORIZED RESELLERS AND DOES NOT SELL OR SUPPLY PRODUCTS TO UNAUTHORIZED RESELLERS. AN ORDER PLACED BY AN UNAUTHORIZED RESELLER WILL BE REJECTED WITHOUT STATING REASONS AND THE SUCH UNAUTHORIZED CUSTOMER MAY BE EXCLUDED BY LATTER HOUSE FROM THE SITE.<br />

          <br />IF A DELIVERED PRODUCT FAILS TO COMPLY WITH THIS LIMITED WARRANTY, YOU MUST NOTIFY LATTER HOUSE THEREOF WITHIN FIVE (5) DAYS. YOU CAN SUBMIT A COMPLAINT BY EMAIL OR IN WRITING. THE CONTACT DETAILS OF LATTER HOUSE ARE PROVIDED AT THE END OF THIS TERMS AND CONDITIONS AND LIMITED WARRANTY POLICY.  LATTER HOUSE WILL RESPOND TO THE COMPLAINT AS SOON AS POSSIBLE, AND IN ANY CASE WITHIN SEVEN (7) DAYS AFTER RECEIPT OF THE COMPLAINT.  IF LATTER HOUSE IS UNABLE TO FORMULATE A SUBSTANTIVE RESPONSE TO THE COMPLAINT WITHIN SUCH PERIOD, LATTER HOUSE WILL CONFIRM RECEIPT OF THE COMPLAINT AND GIVE AN INDICATION OF THE TIME WITHIN WHICH IT EXPECTS TO BE ABLE TO GIVE YOU A SUBSTANTIVE OR DEFINITIVE RESPONSE.  THE WARRANTY LIABILITY OF LATTER HOUSE IS LIMITED TO YOUR PURCHASE PRICE FOR THE PRODUCT UNLESS OTHERWISE PROHIBITED BY LAW.<br />

          <br />PLEASE NOTE: ONLY ITEMS PURCHASED BY THE ORIGINAL PURCHASER ONLATTER HOUSE.COM MAY BE ACCEPTED BY LATTER HOUSE FOR RETURN. IF YOU PURCHASED YOUR PRODUCTS FROM ONE OF OUR AUTHORIZED RETAILERS, PLEASE CONTACT THEM FOR ASSISTANCE.<br />

          <br />IF YOU PURCHASE A PRODUCT FROM AN UNAUTHORIZED RESELLER, THE WARRANTY IS NOT VALID, AND LATTER HOUSE HAS NO WARRANTY OBLIGATION OF ANY KIND. PLEASE BE AWARE THAT THERE ARE SOME WEBSITES OR DEALERS (E.G. EBAY, AMAZON, ETC.) WHO CLAIM TO BE AUTHORIZED RESELLERS BUT ARE NOT. PRODUCTS SOLD ON THESE WEBSITES OR FROM THESE DEALERS DO NOT CARRY A WARRANTY FROM LATTER HOUSE. WHEN YOU PURCHASE PRODUCTS FROM AN UNAUTHORIZED WEBSITE, YOU ARE TAKING A RISK BECAUSE THESE PRODUCTS MAY BE COUNTERFEIT, USED, DEFECTIVE, OR MAY NOT BE DESIGNED OR FIT FOR USE IN YOUR COUNTRY. PLEASE ENSURE THAT YOU ONLY PURCHASE PRODUCTS THROUGH THE SITE OR FROM AN AUTHORIZED RESELLER. IF YOU HAVE ANY QUESTIONS ABOUT AUTHORIZED RESELLERS, PLEASE CONTACT US. THIS DISCLAIMER IS WITHOUT PREJUDICE TO ANY RIGHTS CONSUMERS MAY HAVE AND TO THE EXTENT PERMITTED BY APPLICABLE LAW.<br />

          <br />LATTER HOUSE RESERVES THE RIGHT TO REPAIR, REPLACE OR (PARTIALLY) REFUND THE COST OF A PRODUCT. LATTER HOUSE WILL ONLY PAY THE COSTS OF RETURN AND OTHER SHIPPING COSTS IN CASE OF DEFECTIVE OR MISDESCRIBED PRODUCTS.  THESE RIGHTS SHALL ONLY APPLY TO THE ORIGINAL PURCHASER.<br />

          <br />NO PURCHASE FOR RESALE<br />

          <br />THE PLATFORM IS INTENDED SOLELY FOR LATTER HOUSE TO SELL LATTER HOUSE PRODUCTS DIRECT TO END CONSUMERS, AND THEREFORE PURCHASE OF PRODUCTS FOR RESALE IS STRICTLY PROHIBITED. PURCHASE FOR RESALE MEANS THE PURCHASE OF LATTER HOUSE PRODUCT BY SOMEONE WHO RESELLS, OR INTENDS TO RESELL, THE LATTER HOUSE PRODUCT TO OTHERS (CONSUMERS, BUSINESSES OR ANY THIRD PARTY).  IF LATTER HOUSE BELIEVES YOU ARE INVOLVED IN PURCHASE FOR RESALE, LATTER HOUSE RESERVES THE RIGHT TO TAKE ANY ACTION AGAINST YOU, INCLUDING, WITHOUT LIMITATION, TO RESTRICT SALES TO YOU, CANCEL YOUR ORDERS, AND/OR SUSPEND OR CLOSE YOUR ACCOUNT. <br />

          <br />HOW TO ORDER<br />

          <br />YOU NEED AN E-MAIL ADDRESS OR PHONE NUMBER TO PLACE AN ORDER, AND YOU MAY NEED TO SET YOUR BROWSER TO ACCEPT BOTH (FUNCTIONAL) COOKIES AND POP-UPS IN ORDER TO BE ABLE TO USE ALL THE FUNCTIONALITIES OF THE WEBSITE, WHICH INCLUDES DESIGNING CUSTOMIZED ITEMS, ADDING ITEMS TO YOUR SHOPPING BAG AND SUBMITTING YOUR ORDER.<br />

          <br />WHEN YOU SUBMIT AN ORDER WE WILL SEND YOU AN EMAIL ACKNOWLEDGING RECEIPT OF YOUR ORDER.  OUR ACCEPTANCE OF THE ORDER TAKES PLACE WHEN THE PRODUCTS ARE SHIPPED TO YOU - WE WILL SEND YOU AN EMAIL CONFIRMING THAT THE PRODUCTS HAVE BEEN SHIPPED (“ORDER CONFIRMATION”). AT THIS POINT A CONTRACT, CONTAINING THESE TERMS OF SALE, COMES INTO EXISTENCE AND IS BINDING ON YOU AND US (THE “CONTRACT”). WE RECOMMEND THAT YOU PRINT OR DOWNLOAD A COPY OF THESE TERMS OF SALE AND THE RELEVANT ORDER CONFIRMATION FOR FUTURE REFERENCE.  IF WE ARE UNABLE TO SUPPLY YOU WITH A PRODUCT, WE WILL INFORM YOU OF THIS IN WRITING AND WILL NOT PROCESS THE ORDER.<br />

          <br />OUR RIGHT TO REJECT YOUR ORDER OR CANCEL A CONTRACT<br />

          <br />FULFILLMENT OF ALL ORDERS ON THE PLATFORM IS SUBJECT TO AVAILABILITY. WE EXPLICITLY RESERVE THE RIGHT NOT TO ACCEPT YOUR ORDER FOR ANY REASON. WE ALSO RESERVE THE RIGHT TO CANCEL A CONTRACT BY WRITTEN NOTICE TO YOU IN THE FOLLOWING SITUATIONS, WITHOUT BEING LIABLE FOR ANY DAMAGE OR COSTS OTHER THAN REPAYMENT OF ANY AMOUNT RECEIVED FROM YOU IN RELATION TO THE CONTRACT WE CANCELLED:<br />

          <br />THE PRODUCT IS NOT AVAILABLE / IN STOCK;<br />

          <br />YOUR BILLING INFORMATION IS NOT CORRECT OR NOT VERIFIABLE;<br />

          <br />YOUR ORDER IS FLAGGED UP BY OUR SECURITY SYSTEMS AS AN UNUSUAL ORDER OR AN ORDER SUSCEPTIBLE TO FRAUD;<br />

          <br />YOUR BANK TRANSFER PAYMENT IS NOT RECEIVED WITHIN 12 CALENDAR DAYS AFTER ACCEPTANCE OF YOUR ORDER;<br />

          <br />WE BELIEVE YOU ARE UNDER THE LEGAL AGE IN YOUR COUNTRY;<br />

          <br />WE BELIEVE THAT YOU ARE A RESELLER;<br />

          <br />THERE WAS AN ERROR IN THE PRICE DISPLAYED ON THE PLATFORM;<br />

          <br />WE COULD NOT DELIVER TO THE ADDRESS PROVIDED BY YOU;<br />

          <br />DUE TO AN EVENT OUTSIDE OUR CONTROL (SEE BELOW);<br />

          <br />YOU HAVE VIOLATED THESE TERMS OF SALE OR TERMS OF USE OR OUR PRIVACY POLICY; OR<br />

          <br />IN THE EVENT OF MISSPELLING, PRICING OR OTHER ERRORS OR MISTAKES IN THE PLATFORM INFORMATION.<br />

          <br />DATA CHECK<br />

          <br />WHEN YOU SEND US YOUR ORDER, WE MAY RUN SOME CHECKS ON IT BEFORE IT IS FULFILLED. THESE CHECKS MAY INCLUDE VERIFYING YOUR ADDRESS AND CHECKING FOR FRAUD.  WE RUN PARTLY AUTOMATED CHECKS ON ALL PURCHASES TO FILTER OUT UNUSUAL OR SUSPECT TRANSACTIONS, OR TRANSACTIONS WHICH CAN BE IDENTIFIED AS SUSCEPTIBLE TO FRAUD. SUSPECTED FRAUD ON THE PLATFORM WILL BE INVESTIGATED AND IF NECESSARY PROSECUTED.<br />

          <br />TITLE TRANSFER & RISK OF LOSS<br />

          <br />WITH THE EXCEPTION OF PRODUCTS PICKED UP AT LATTER HOUSE-BRANDED STORES, THE TITLE AND RISK OF LOSS FOR PRODUCTS PURCHASED FROM LATTER HOUSE PASS TO YOU UPON OUR DELIVERY TO THE CARRIER.  TITLE AND RISK OF LOSS FOR PRODUCTS PURCHASED ONLINE AND PICKED UP AT LATTER HOUSE-BRANDED STORES WILL PASS TO YOU UPON YOUR AUTHORIZED RECEIPT OF THOSE PRODUCTS.  TITLE TO PRODUCT(S) WILL NOT TRANSFER UNTIL FULL PAYMENT HAS BEEN RECEIVED.<br />

          <br />PRICE/PAYMENT<br />

          <br />PAYMENT METHODS<br />

          <br />YOU CAN FIND THE AVAILABLE PAYMENT METHODS FOR EACH COUNTRY IN THE CHECKOUT SECTION OF LATTER HOUSE.COM (THE “WEBSITE”). WE DO NOT ACCEPT ANY METHOD OF PAYMENT OTHER THAN THOSE LISTED IN THE HELP SECTION. PLEASE DO NOT TRY TO PAY BY ANY OTHER WAY THAN SPECIFIED THERE. IF YOU DO, WE WILL NOT BE LIABLE FOR LOSS OF THE PAYMENT OR ANY OTHER DAMAGES THAT MAY RESULT FROM THIS ACTION.<br />

          <br />PAYMENT PROCESSING<br />

          <br />EXCEPT WITH RESPECT TO PRE-ORDERED PRODUCTS, IF YOU PAY BY CREDIT/DEBIT CARD, WE WILL DEDUCT THE AMOUNT DUE FROM YOUR ACCOUNT AS SOON AS YOUR ORDER LEAVES OUR WAREHOUSE.  IF YOU PAY BY BANK TRANSFER (ONLY AVAILABLE FOR BULK ORDERS), WE WILL START DELIVERY AFTER WE RECEIVE YOUR PAYMENT. THIS MAY TAKE SEVERAL DAYS. IN THE EVENT THAT NO PAYMENT HAS BEEN RECEIVED WITHIN 12 CALENDAR DAYS AFTER YOU SUBMITTED YOUR ORDER, YOUR PURCHASE WILL AUTOMATICALLY BE CANCELLED.  PAYMENTS CAN ONLY BE PROCESSED IF THE BILLING INFORMATION CAN BE VERIFIED<br />

          <br />PRICES AND CURRENCY<br />

          <br />THE PRODUCT PRICES DISPLAYED ON THE PLATFORM ARE INCLUSIVE OF VALUE-ADDED TAX (VAT), AS APPLICABLE. SHIPPING RATES ARE APPLIED PER ORDER. THE EXACT SHIPPING RATES DEPEND ON THE COUNTRY WHERE YOUR ORDER IS BEING DELIVERED TO. FOR DETAILS ON SHIPPING RATES PER COUNTRY SEE THE HELP SECTION OF THE WEBSITE.<br />

          <br />PRICES ARE QUOTED IN LOCAL CURRENCY. IF YOU CHANGE THE COUNTRY OF DELIVERY WHILE BROWSING OR DURING CHECK OUT, PRICES FROM THAT MOMENT MAY BE QUOTED IN A DIFFERENT CURRENCY. PLEASE NOTE THAT CHANGING THE COUNTRY OF DELIVERY MAY HAVE AN INFLUENCE ON THE PRICE DUE TO A CHANGE IN CURRENCY OR TO COUNTRY SPECIFIC PRICING.<br />

          <br />YOUR TOTAL PRICE<br />

          <br />THE TOTAL PRICE SPECIFIED IN THE FINAL CHECK OUT SCREEN INCLUDES TAX AND SHIPPING COSTS. THIS PRICE WILL BE RECORDED IN THE ORDER CONFIRMATION, WHICH WE RECOMMEND YOU PRINT OR DOWNLOAD FOR FUTURE REFERENCE. IF PAYING BY CREDIT CARD, THE TOTAL AMOUNT FOR YOUR ENTIRE ORDER WILL BE REFLECTED ON YOUR STATEMENT IN YOUR LOCAL CURRENCY.<br />

          <br />IF YOUR LOCAL CURRENCY IS DIFFERENT FROM THE CURRENCY IN WHICH THE PRICES ARE QUOTED, YOUR BANK WILL APPLY THE EXCHANGE RATE APPLICABLE PER THE DATE OF PURCHASE. YOUR BANK MAY APPLY A DIFFERENT EXCHANGE RATE, WHICH IS BEYOND OUR CONTROL.<br />

          <br />PRICE CHANGES<br />

          <br />THE PRICES OF THE PRODUCTS WILL BE AS DISPLAYED ON THE PLATFORM. PRICES MAY CHANGE FROM TIME TO TIME, BUT CHANGES WILL NOT AFFECT ANY ORDER WHICH WE HAVE CONFIRMED IN AN ORDER CONFIRMATION.<br />

          <br />SHIPPING & DELIVERY<br />

          <br />DELIVERY – WHERE AND WHEN<br />

          <br />WE DO NOT SHIP ON CERTAIN PUBLIC HOLIDAYS. PLEASE REFER TO THE HELP SECTION OF THE WEBSITE FOR DATES AND THE AVAILABLE DELIVERY TIMES AND METHODS. WE CAN ONLY FULFILL AN ORDER TO A DELIVERY ADDRESS WHICH IS A HOME OR OFFICE ADDRESS IN ONE OF THE COUNTRIES LISTED IN THE HELP SECTION OF THE WEBSITE.<br />

          <br />SPLIT DELIVERY<br />

          <br />WHERE POSSIBLE, WE TRY TO DELIVER ALL ITEMS WHICH YOU HAVE ORDERED AT THE SAME TIME. HOWEVER, PLEASE NOTE THAT DUE TO THE FACT THAT CUSTOMIZED PRODUCTS ARE MANUFACTURED AT DIFFERENT FACTORIES, AN ORDER FOR MULTIPLE CUSTOMIZED PRODUCTS MAY RESULT IN SPLIT SHIPMENTS.<br />

 

          <br />WE RESERVE THE RIGHT TO SPLIT THE DELIVERY OF YOUR ORDER, FOR INSTANCE IF PART OF YOUR ORDER IS DELAYED OR UNAVAILABLE. IN THE EVENT THAT WE SPLIT YOUR ORDER, WE WILL NOTIFY YOU OF OUR INTENTION TO DO SO BY SENDING YOU AN E-MAIL TO THE E-MAIL ADDRESS PROVIDED BY YOU AT THE TIME YOUR ORDER WAS PLACED.<br />

          <br />INSPECTION UPON DELIVERY<br />

          <br />UPON DELIVERY, PLEASE INSPECT THE PACKAGING FOR DAMAGE. IF IT APPEARS THAT THE PRODUCTS ARE DAMAGED, PLEASE DO NOT ACCEPT THE SHIPMENT.<br />

          <br />WE WILL ENSURE YOUR PACKAGE IS SENT OUT IN TIME BUT ONCE THE PACKAGE LEAVES OUR FACILITY, IT FALLS UNDER THE LIABILITY OF THE COURIER AND CAN BE SUBJECT TO ISSUES THAT ARE OUT OF OUR CONTROL. YOU WILL NEED TO CONTACT THE ACCORDING SHIPPING SERVICE FOR UPDATES ON ANY DELAYS OR SHIPPING ERRORS.<br />

          <br />PLEASE MAKE INQUIRIES ON IDLE PACKAGES WITHIN 30 DAYS FROM THE ORDER DATE.<br />

          <br />RETURNS & CANCELLATIONS<br />

          <br />CANCELLING ORDER BEFORE DELIVERY<br />

          <br />ALL SALES ARE FINAL UNLESS THERE WAS AN ISSUE WITH WRONG SIZE SHIPPED OR DAMAGE OF GOODS.<br />

          <br />CUSTOMIZED ORDERS CANNOT BE CANCELLED BEFORE SHIPMENT, BECAUSE WE START BUILDING THE CUSTOMIZED PRODUCTS IMMEDIATELY AFTER RECEIVING THE ORDER. YOU ARE HOWEVER ENTITLED TO RETURN YOUR ORDER IN ACCORDANCE WITH THE RETURN PROCEDURES AND CONDITIONS BELOW.<br />

          <br />RETURNING ORDERS AFTER DELIVERY – DEFECTIVE PRODUCTS<br />

          <br />YOU ARE ENTITLED TO RETURN PRODUCTS DELIVERED TO YOU IN THE EVENT THAT THEY ARE DEFECTIVE OR OTHERWISE NOT IN CONFORMITY WITH YOUR ORDER WHEN YOU RECEIVED THEM. THIS DOES NOT AFFECT YOUR STATUTORY RIGHTS. IN THE EVENT YOUR CLAIM IS JUSTIFIED, THE PURCHASE PRICE AND THE SHIPPING COSTS WILL BE REFUNDED. FOR PRACTICAL INFORMATION ON HOW TO RETURN, SEE THE HELP SECTION OF THE WEBSITE.<br />

          <br />REFUND INFORMATION<br />

          <br />ALL SALES ARE FINAL BUT IN THE EVENT CUSTOMER SERVICE HAS ISSUED A REFUND THEY WILL BE ISSUED BASED ON THE ORIGINAL FORM OF PAYMENT. IF YOU PAID VIA BANK TRANSFER YOU NEED TO GIVE THIS INFORMATION TO CUSTOMER SERVICE WHEN YOU INITIATE THE RETURN SO THAT WE CAN REFUND THE MONEY DIRECTLY TO YOUR ACCOUNT.<br />

          <br />CONDITIONS APPLICABLE TO PRE-ORDERED PRODUCTS<br />

          <br />PRE-ORDER IS THE PROCESS BY WHICH YOU ARE ABLE TO ORDER A PRODUCT IN ADVANCE OF THE SCHEDULED RETAIL LAUNCH. DUE TO THE NATURE OF PRE ORDERING, THE FOLLOWING SPECIFIC CONDITIONS APPLY TO PRE-ORDERED PRODUCTS:<br />

          <br />DELIVERY. PRE-ORDERED PRODUCTS ARE TARGETED TO BE DELIVERED BEFORE THE RETAIL LAUNCH DATE, PROVIDED THAT WE HAVE RECEIVED YOUR PAYMENT AT LEAST 3 WORKING DAYS BEFORE SUCH DATE. CONCRETE DELIVERY TIMES DEPEND ON THE MOMENT THE PRODUCT IS AVAILABLE IN OUR WAREHOUSE. STANDARD DELIVERY TIMELINES WILL APPLY FROM THE MOMENT THE PRE-ORDERED PRODUCT IS AVAILABLE IN OUR WAREHOUSE. THIS INFORMATION IS BEST ESTIMATES ONLY, TIMELINES ARE NOT BINDING.<br />

          <br />PAYMENT. YOUR PAYMENT WILL BE DEDUCTED AS SOON AS THE ORDER IS RECEIVED (OR, IN THE EVENT OF BANK TRANSFER, AS SOON AS POSSIBLE). WE WILL NOT START THE EXECUTION OF YOUR ORDER PRIOR TO HAVING RECEIVED PAYMENT. FOR BANK TRANSFERS THIS MAY MEAN THAT DELIVERY WILL BE LATER THAN SET OUT UNDER THE BULLET POINT ABOVE.<br />

          <br />EVENTS OUTSIDE OUR CONTROL<br />

          <br />AN EVENT OUTSIDE OUR CONTROL MEANS ANY ACT OR EVENT BEYOND OUR REASONABLE CONTROL, INCLUDING WITHOUT LIMITATION STRIKES, LOCK-OUTS OR OTHER INDUSTRIAL ACTION BY THIRD PARTIES, CIVIL COMMOTION, RIOT, INVASION, TERRORIST ATTACK OR THREAT OF TERRORIST ATTACK, WAR (WHETHER DECLARED OR NOT) OR THREAT OR PREPARATION FOR WAR, FIRE, EXPLOSION, STORM, FLOOD, EARTHQUAKE, SUBSIDENCE, EPIDEMIC, PANDEMIC, OR OTHER NATURAL DISASTER, OR FAILURE OF PUBLIC OR PRIVATE TELECOMMUNICATIONS NETWORKS.<br />

          <br />IF AN EVENT OUTSIDE OUR CONTROL TAKES PLACE THAT AFFECTS THE PERFORMANCE OF OUR OBLIGATIONS UNDER THESE TERMS OF SALE:<br />

          <br />A) WE WILL CONTACT YOU AS SOON AS REASONABLY POSSIBLE TO NOTIFY YOU; AND<br />
          <br />B) OUR OBLIGATIONS UNDER THESE GENERAL CONDITIONS WILL BE SUSPENDED AND THE TIME FOR PERFORMANCE OF OUR OBLIGATIONS WILL BE EXTENDED FOR THE DURATION OF THE EVENT OUTSIDE OUR CONTROL.
          <br />WHERE THE EVENT OUTSIDE OUR CONTROL AFFECTS OUR DELIVERY OF A PRODUCT TO YOU, WE WILL ARRANGE A NEW DELIVERY DATE WITH YOU AFTER THE EVENT OUTSIDE OUR CONTROL IS OVER.  YOU MAY CANCEL THE CONTRACT IF AN EVENT OUTSIDE OUR CONTROL TAKES PLACE AND YOU NO LONGER WISH US TO PROVIDE THE PRODUCTS. PLEASE SEE YOUR CANCELLATION RIGHTS UNDER CANCELLATION ABOVE.<br />

          <br />OTHER IMPORTANT TERMS<br />

          <br />WE MAY TRANSFER OUR RIGHTS AND OBLIGATIONS UNDER A CONTRACT TO ANOTHER ORGANIZATION, BUT THIS WILL NOT AFFECT YOUR RIGHTS OR OUR OBLIGATIONS UNDER THESE TERMS OF SALE.<br />

          <br />YOU MAY ONLY TRANSFER YOUR RIGHTS OR YOUR OBLIGATIONS UNDER THESE TERMS OF SALE TO ANOTHER PERSON IF WE AGREE IN WRITING.<br />

          <br />EACH OF THE PARAGRAPHS OF THIS TERMS OF SALE OPERATES SEPARATELY. IF ANY COURT OR RELEVANT AUTHORITY DECIDES THAT ANY OF THEM ARE UNLAWFUL OR UNENFORCEABLE, THE REMAINING PARAGRAPHS WILL REMAIN IN FULL FORCE AND EFFECT.<br />

          <br />IF WE FAIL TO INSIST THAT YOU PERFORM ANY OF YOUR OBLIGATIONS UNDER THESE TERMS OF SALE, OR IF WE DO NOT ENFORCE OUR RIGHTS AGAINST YOU, OR IF WE DELAY IN DOING SO, THAT WILL NOT MEAN THAT WE HAVE WAIVED OUR RIGHTS AGAINST YOU AND WILL NOT MEAN THAT YOU DO NOT HAVE TO COMPLY WITH THOSE OBLIGATIONS.<br />

          <br />IF WE DO WAIVE A DEFAULT BY YOU, WE WILL ONLY DO SO IN WRITING, AND THAT WILL NOT MEAN THAT WE WILL AUTOMATICALLY WAIVE ANY LATER DEFAULT BY YOU. WE WILL NOT FILE A COPY OF THE CONTRACT BETWEEN US.<br />

          <br />COUNTRY-SPECIFIC TERMS<br />

 

          <br />IF YOU ARE LOCATED IN ONE OF THE FOLLOWING COUNTRIES, THE ADDITIONAL TERMS BELOW WILL APPLY AND OVERRIDE ANY INCONSISTENT TERMS ABOVE. <br />

          <br />DOMINICAN REPUBLIC<br />

          <br />THE SECTION ABOVE TITLED “PAYMENT PROCESSING” IS MODIFIED BY ADDING THE FOLLOWING NEW SECTION:<br />

          <br />“NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THESE TERMS OF USE, FROM THE MOMENT YOU PLACE AN ORDER AND THE DELIVERY OF THE PRODUCT, YOU HAVE THREE (3) DAYS FROM THE ORDER DATE TO CANCEL THE ORDER, FREE OF CHARGE. IN ADDITION, YOU MAY RETURN YOUR ORDER WITHIN SEVEN (7) DAYS AFTER RECEIPT, WITHOUT PENALTY.”<br />

          <br />KOREA<br />

          <br />THE SECTION ABOVE TITLED “RETURNS & CANCELLATIONS: CANCELLING ORDER BEFORE DELIVERY” IS MODIFIED BY ADDING THE FOLLOWING NEW SECTION:<br />

          <br />“NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THESE TERMS OF USE, YOU HAVE THE LEGAL RIGHT TO CANCEL AN ORDER WITHIN 7 DAYS FROM THE DAY WHEN THE GOODS ARE RECEIVED, PROVIDED THAT YOU WILL NOT BE ENTITLED TO THE RIGHT TO CANCEL UNDER THE FOLLOWING CIRCUMSTANCES:<br />

          <br />WHERE THE GOODS HAVE BEEN DESTROYED OR DAMAGED DUE TO A CAUSE ATTRIBUTABLE TO YOU;<br />

          <br />WHERE THE VALUE OF THE GOODS HAS SUBSTANTIALLY DECREASED DUE TO A CAUSE ATTRIBUTABLE TO YOU;<br />

          <br />WHERE THE VALUE OF THE GOODS HAS SUBSTANTIALLY DECREASED TO CAUSE DIFFICULTY IN RESALE DUE TO THE ELAPSE OF TIME;<br />

          <br />WHERE THE PACKAGE OF THE REPRODUCIBLE GOODS HAS BEEN DESTROYED; OR<br />

          <br />WHERE THE CANCELLATION OF ORDERS FOR GOODS THAT ARE EXPECTED TO CAUSE SIGNIFICANT AND UNRECOVERABLE LOSS TO LATTER HOUSE – SUCH AS CUSTOMIZED GOODS PRODUCED SPECIFICALLY FOR YOU PURSUANT TO YOUR ORDER – AND WHERE THIS FACT HAS BEEN PROVIDED TO YOU IN ADVANCE CONCERNING THE SUBJECT TRANSACTION AND YOUR CONSENT HAS BEEN OBTAINED IN WRITING (INCLUDING IN ELECTRONIC FORMAT).”<br />

          <br />TERMS OF USE<br />

          <br />LATTER HOUSE AND ITS AFFILIATES ("LATTER HOUSE") OPERATES THE WEBSITE AT WWW.LATTER HOUSE.COM (THE "WEBSITE" OR "SITE"). TO ASSIST YOU IN USING THE WEBSITE AND ASSOCIATED SERVICES, AND TO ENSURE A CLEAR UNDERSTANDING OF THE RELATIONSHIP ARISING FROM YOUR USE OF THE WEBSITE AND PARTICIPATION IN THE SERVICES, WE HAVE CREATED (I) THESE TERMS OF USE (THE "TERMS OF USE" OR "TERMS"), (II) THE TERMS OF SALE SET FORTH ABOVE, AND (III) A PRIVACY POLICY. OUR PRIVACY POLICY EXPLAINS HOW WE TREAT INFORMATION YOU PROVIDE TO US THROUGH THE SITE, AND OUR TERMS GOVERN YOUR USE OF OUR SITE AND PARTICIPATION IN OUR SERVICES. OUR TERMS AND PRIVACY POLICY APPLY TO ANY VISITOR TO THE WEBSITE (COLLECTIVELY, "YOU"), INCLUDING CASUAL VISITORS TO OUR SITE WHO DO NOT PARTICIPATE IN THE SERVICES. THE TERMS "LATTER HOUSE," "WE" AND "US" REFER TO LATTER HOUSE.<br />

          <br />PLEASE READ THIS DOCUMENT CAREFULLY BEFORE YOU ACCESS OR USE THE WEBSITE. BY ACCESSING THE WEBSITE, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS AND CONDITIONS, PLEASE DO NOT ACCESS OUR WEBSITE.<br />

          <br />YOUR AGREEMENT. THESE TERMS GOVERN: (I) YOUR USE OF THE WEBSITE, (II) YOUR RECEIPT OF AND PARTICIPATION IN LATTER HOUSE’S SERVICES OFFERED THROUGH THE WEBSITE (THE "SERVICES"), (III) YOUR PROVISION OF INFORMATION IN CONNECTION WITH USING THE WEBSITE (COLLECTIVELY, THE "USER CONTENT "); AND (IV) YOUR USE OF INFORMATION OBTAINED THROUGH THE WEBSITE, INCLUDING INFORMATION, SOFTWARE, ARTWORK, TEXT, VIDEO, AUDIO, PICTURES, CONTENT, TRADEMARKS, TRADE DRESS, AND OTHER INTELLECTUAL PROPERTY OWNED BY OMERTA LTD OR ITS LICENSORS AND MADE AVAILABLE TO YOU THROUGH THE WEBSITE (COLLECTIVELY, THE "LATTER HOUSE CONTENT"). PLEASE READ THESE TERMS CAREFULLY; THEY IMPOSE LEGAL OBLIGATIONS ON YOU AND ON LATTER HOUSE, AND ESTABLISH OUR LEGAL RELATIONSHIP. BY ACCESSING OUR WEBSITE, YOU ARE ACKNOWLEDGING THAT YOU HAVE READ AND UNDERSTOOD THESE TERMS AND AGREE TO BE LEGALLY BOUND BY THEM.<br />

          <br />OWNERSHIP; RESERVATION OF RIGHTS.THE INFORMATION, SOFTWARE, ARTWORK, TEXT, VIDEO, AUDIO, PICTURES, TRADEMARKS, TRADE DRESS, AND OTHER INTELLECTUAL PROPERTY EMBODIED IN THE WEBSITE, SERVICES, OR THE LATTER HOUSE CONTENT, ARE THE PROPRIETARY PROPERTY OF LATTER HOUSE AND ITS LICENSORS, AND ARE PROTECTED BY U.S. AND INTERNATIONAL COPYRIGHT AND OTHER INTELLECTUAL PROPERTY LAWS, OR ARE USED UNDER THE PRINCIPLES OF FAIR USE. LATTER HOUSE AND ITS LICENSORS RETAIN ALL RIGHTS WITH RESPECT TO THE WEBSITE, SERVICES, AND THE LATTER HOUSE CONTENT EXCEPT THOSE EXPRESSLY GRANTED TO YOU IN THESE TERMS. YOU AGREE NOT TO DUPLICATE, PUBLISH, DISPLAY, DISTRIBUTE, MODIFY, OR CREATE DERIVATIVE WORKS FROM THE MATERIAL PRESENTED THROUGH THE SITE AND/OR THROUGH THE SERVICES UNLESS SPECIFICALLY AUTHORIZED IN WRITING BY LATTER HOUSE.<br />

          <br />GRANT OF RIGHTS<br />

          <br />GRANT OF RIGHTS TO LATTER HOUSE IN USER CONTENT.BY SUBMITTING USER CONTENT WHEN PARTICIPATING IN THE SERVICES, UPLOADING FILES, OR OTHERWISE (IF SUCH FEATURES ARE AVAILABLE TO YOU), YOU GRANT LATTER HOUSE THE RIGHT TO USE, COPY, REFORMAT, INDEX, MODIFY, DISPLAY, AND DISTRIBUTE YOUR USER CONTENT FOR THE PURPOSES OF PROVIDING OUR SERVICES. NO COMPENSATION WILL BE PAID WITH RESPECT TO LATTER HOUSE’S USE OF YOUR USER CONTENT UNDER THIS GRANT. YOU REPRESENT AND WARRANT THAT YOU OWN ALL RIGHTS NEEDED TO PROVIDE THE GRANT SET OUT IN THIS SECTION  (GRANT OF RIGHTS TO LATTER HOUSE IN USER CONTENT).<br />

          <br />CODE OF CONDUCT. AS A CONDITION TO YOUR USE OF THE WEBSITE AND THE SERVICES, YOU AGREE TO FOLLOW OUR CODE OF CONDUCT, SET OUT BELOW. UNDER THIS CODE, YOU WILL NOT:<br />

          <br />UPLOAD, EMAIL, OR OTHERWISE TRANSMIT ANY IMAGES OR OTHER USER CONTENT THAT IS UNLAWFUL, OBSCENE, HARMFUL, HATEFUL, INVADES THE PRIVACY OF ANY THIRD PARTY, CONTAINS NUDITY OR PORNOGRAPHY, OR IS OTHERWISE OBJECTIONABLE.
DISSEMINATE MATERIALS THAT IMPACT OR INVADE THE PRIVACY OF OTHERS, SUCH AS PHOTOGRAPHS, VIDEO CLIPS, SOUND RECORDINGS, PERSONALLY IDENTIFIABLE INFORMATION, OR OTHER MATERIALS THAT REVEAL PERSONAL, PRIVATE, OR SENSITIVE INFORMATION ABOUT ANOTHER PERSON, WITHOUT THAT PERSON'S CONSENT.
SUBMIT MATERIAL THAT IS INTENTIONALLY FALSE, DEFAMATORY, UNLAWFULLY THREATENING, OR UNLAWFULLY HARASSING.
INFRINGE ANY THIRD PARTY'S COPYRIGHT, PATENT, TRADEMARK, TRADE SECRET, OR OTHER PROPRIETARY RIGHTS OR RIGHTS OF PUBLICITY OR PRIVACY.
SUBMIT ELECTRONIC MATERIALS – SUCH AS MUSIC, VIDEOS, GAMES, IMAGES, AND TEXT IN ELECTRONIC FORM – THAT CAN EASILY BE COPIED, MODIFIED, AND SENT OVER NETWORKS (SUCH AS THE INTERNET). THESE ELECTRONIC MATERIALS ARE THUS EXTREMELY VULNERABLE TO UNAUTHORIZED DISTRIBUTION AND COPYRIGHT INFRINGEMENT. THESE MATERIALS MAY NOT BE TRANSMITTED OVER THE WEBSITE WITHOUT THE COPYRIGHT OWNER'S PERMISSION.
TRANSMIT MATERIAL THAT CONTAINS VIRUSES, TROJAN HORSES, WORMS, TIME BOMBS, CANCELBOTS, OR OTHER COMPUTER-PROGRAMMING ROUTINES THAT ARE INTENDED TO DAMAGE, DETRIMENTALLY INTERFERE WITH, SURREPTITIOUSLY INTERCEPT, OR EXPROPRIATE ANY SYSTEM, DATA, OR PERSONAL INFORMATION.
USE THE WEBSITE TO ARTIFICIALLY GENERATE TRAFFIC OR PAGE LINKS TO A WEBSITE OR FOR ANY OTHER PURPOSE NOT EXPRESSLY ALLOWED UNDER THESE TERMS.
USE THE WEBSITE IN A MANNER THAT COULD DISABLE, OVERBURDEN, OR IMPAIR THE WEBSITE OR SERVICES, OR INTERFERE WITH ANY OTHER PARTY'S USE AND ENJOYMENT OF THE WEBSITE AND SERVICES, SUCH AS THROUGH SENDING "SPAM" EMAIL.
USE THE WEBSITE TO TEST OR REVERSE ENGINEER THE WEBSITE IN ORDER TO FIND LIMITATIONS, VULNERABILITIES, OR TO EVADE FILTERING CAPABILITIES.
SEEK TO OBTAIN ACCESS TO ANY MATERIALS OR INFORMATION THROUGH "HACKING," "DATA HARVESTING," OR THROUGH OTHER MEANS WE HAVE NOT INTENTIONALLY MADE AVAILABLE TO YOU THROUGH THE WEBSITE.
USE THE WEBSITE FOR ANY PURPOSE THAT IS UNLAWFUL OR PROHIBITED BY THESE TERMS. FOR EXAMPLE, YOU WILL NOT USE THE WEBSITE TO VIOLATE ANY LAW, STATUTE, OR REGULATION (INCLUDING, WITHOUT LIMITATION, THOSE GOVERNING EXPORT CONTROL, CONSUMER PROTECTION, UNFAIR COMPETITION, ANTI-DISCRIMINATION, OR FALSE ADVERTISING).
MONITORING; REVOCATION OR SUSPENSION OF USE PRIVILEGES.WE RESERVE THE RIGHT AT ANY TIME TO (I) MONITOR YOUR USE OF THE WEBSITE, AND (II) TERMINATE OR SUSPEND YOUR USE OF SOME OR ALL SERVICES IF YOU ENGAGE IN ACTIVITIES THAT WE CONCLUDE, IN OUR DISCRETION, BREACH OUR CODE OF CONDUCT OR OTHERWISE VIOLATE THESE TERMS OR OUR PRIVACY POLICY.<br />

<br />ALTHOUGH WE HAVE NO – AND ASSUME NO – OBLIGATION TO MONITOR ACTIVITIES ON THE WEBSITE, PLEASE UNDERSTAND THAT WE MAY EMPLOY FILTERS DESIGNED TO DETECT AND BLOCK INAPPROPRIATE CONTENT UNDER THIS CODE OF CONDUCT. WE RESERVE THE RIGHT TO REQUEST EDITS TO REMOVE ANY INFORMATION OR MATERIALS, IN WHOLE OR IN PART, THAT WE BELIEVE, IN OUR SOLE DISCRETION, ARE INCOMPATIBLE WITH OUR CODE OF CONDUCT. IF YOU DO NOT REMOVE OBJECTIONABLE CONTENT IN RESPONSE TO OUR REASONABLE REQUESTS, WE MAY IN OUR SOLE DISCRETION DECIDE TO TERMINATE YOUR USE OF SOME OR ALL OF THE SERVICES AT ISSUE.<br />

<br />USERS SHOULD ALSO UNDERSTAND THAT OUR CODE OF CONDUCT IS BASED IN MANY INSTANCES ON PRINCIPLES OF APPLICABLE LAW. USERS WHO VIOLATE OUR CODE OF CONDUCT ACCORDINGLY MAY BE SUBJECT TO APPLICABLE LAW. LATTER HOUSE MARKET RESERVES THE RIGHT AT ALL TIMES TO DISCLOSE INFORMATION IT DEEMS NECESSARY TO SATISFY ANY APPLICABLE LAW, REGULATION, LEGAL PROCESS, OR GOVERNMENTAL REQUEST, CONSISTENT WITH OUR PRIVACY POLICY.<br />

<br />REPORTS AND COMPLAINTS. IF YOU BELIEVE THAT A USER HAS ACTED INAPPROPRIATELY, SUCH AS BY VIOLATING OUR CODE OF CONDUCT, YOU MAY REPORT YOUR CONCERNS BY CONTACTING US IN ACCORDANCE WITH THE CONTACT US SECTION BELOW.<br />

<br />LINKS TO THIRD-PARTY SITES. THE WEBSITE MAY ALSO CONTAIN LINKS OR PRODUCE SEARCH RESULTS THAT REFERENCE LINKS TO THIRD PARTY WEBSITES (COLLECTIVELY "LINKED SITES"), SUCH AS THOSE TO VISIT OUR PAGES ON SOCIAL MEDIA WEBSITES. LATTER HOUSE HAS NO CONTROL OVER THESE LINKED SITES OR THEIR CONTENT AND DOES NOT ASSUME RESPONSIBILITY OR LIABILITY FOR ANY CONTENT, OPINIONS, MATERIAL AVAILABLE ON LINKED SITES, OR SUCH LINKED SITES' PRIVACY PRACTICES WITH RESPECT TO INFORMATION THAT YOU PROVIDE TO THE LINKED SITES. LATTER HOUSE DOES NOT ENDORSE THE CONTENT OF ANY LINKED SITE, NOR DOES LATTER HOUSE WARRANT THAT A LINKED SITE WILL BE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL CODE THAT CAN IMPACT YOUR COMPUTER OR OTHER WEB-ACCESS DEVICE. BY USING THE WEBSITE TO SEARCH FOR OR LINK TO ANOTHER SITE, YOU AGREE AND UNDERSTAND THAT SUCH USE IS AT YOUR OWN RISK. FOR EXAMPLE, IF YOU SUBMIT PERSONALLY IDENTIFIABLE INFORMATION TO A LINKED SITE, THEN THE INFORMATION THAT YOU SUBMIT SHALL BE GOVERNED BY THE LINKED SITE'S PRIVACY POLICY AND TERMS OF USE, AND NOT BY LATTER HOUSE’S PRIVACY POLICY AND TERMS OF USE.<br />

<br />USER CONDUCT; USER DISPUTES.LATTER HOUSE IS NOT RESPONSIBLE FOR AND IS NOT LIABLE FOR USER CONTENT OR USER CONDUCT. YOU ARE SOLELY RESPONSIBLE FOR YOUR USER CONTENT, CONDUCT, AND INTERACTION WITH OTHER SITE VISITORS, BOTH ONLINE AND OFFLINE. WE HAVE NO OBLIGATION TO BECOME INVOLVED IN DISPUTES BETWEEN SITE VISITORS. IF YOU HAVE A DISPUTE WITH ONE OR MORE SITE VISITORS, YOU RELEASE LATTER HOUSE (AND OUR OFFICERS, DIRECTORS, AGENTS, EMPLOYEES, SUBSIDIARIES, AND AFFILIATES) FROM CLAIMS, DEMANDS, AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTE.<br />

<br />LIMITED WARRANTY AND DISCLAIMER.LATTER HOUSE DOES NOT PROMISE THAT THE WEBSITE, PRODUCTS, OR SERVICES WILL BE ERROR-FREE OR UNINTERRUPTED. THE WEBSITE AND ALL SERVICES AND CONTENT WITHIN IT ARE DELIVERED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WHEN YOU ACCESS THE WEBSITE, YOU DO SO AT YOUR OWN RISK. LATTER HOUSE DOES NOT WARRANT OR REPRESENT THAT MATERIALS YOU DOWNLOAD FROM THE SITE WILL BE FREE OF VIRUSES OR OTHER HARMFUL FEATURES.<br />

<br />LATTER HOUSE DISCLAIMS: (I) ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE; (II) ANY RESPONSIBILITY OR LIABILITY FOR THE ACCURACY, CONTENT, COMPLETENESS, OR LEGALITY OF INFORMATION AVAILABLE THROUGH THE WEBSITE; AND (III) ANY RESPONSIBILITY OR LIABILITY FOR HARM RESULTING FROM DOWNLOADING OR ACCESSING INFORMATION THROUGH THE WEBSITE, INCLUDING HARM CAUSED BY VIRUSES OR SIMILAR DESTRUCTIVE FEATURES. YOU EXPRESSLY AGREE THAT USE OF THE WEBSITE AND RELATED SERVICES AND CONTENT IS AT YOUR SOLE RISK.<br />

<br />LIMITATION OF LIABILITY.UNDER NO CIRCUMSTANCES INCLUDING, BUT NOT LIMITED TO, BREACH OF CONTRACT, TORT, OR NEGLIGENCE, WILL LATTER HOUSE BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING LOST PROFITS) THAT ARISE OUT OF OR ARE RELATED TO YOUR USE OF THE WEBSITE AND RELATED SERVICES AND CONTENT.<br />

<br />YOU AGREE TO DEFEND, INDEMNIFY, AND HOLD LATTER HOUSE AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, AGENTS, AND EMPLOYEES HARMLESS FROM ANY LIABILITY TO THIRD PARTIES, INCLUDING REASONABLE ATTORNEYS' FEES, ARISING FROM OR RELATED TO YOUR BREACH OF THESE TERMS.<br />

<br />FORCE MAJEURE. NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS AND CONDITIONS AND LIMITED WARRANTY, NEITHER PARTY WILL BE LIABLE TO THE OTHER PARTY FOR ANY DELAY IN PERFORMING OR FAILURE TO PERFORM ANY OF ITS OBLIGATIONS UNDER THIS AGREEMENT TO THE EXTENT PERFORMANCE IS DELAYED OR PREVENTED DUE TO FORCE MAJEURE. "FORCE MAJEURE" WILL MEAN CAUSES THAT ARE BEYOND THE REASONABLE CONTROL OF THE PARTY CLAIMING FORCE MAJEURE AND THAT COULD NOT HAVE BEEN AVOIDED OR PREVENTED BY REASONABLE FORESIGHT, PLANNING OR IMPLEMENTATION BY THE PARTY CLAIMING FORCE MAJEURE, INCLUDING WITHOUT LIMITATION: (A) ANY ACT OF GOD, FIRE, EXPLOSION, LIGHTNING, STORM, FLOOD, EARTHQUAKE, OR ACCIDENT; (B) WAR, TERRORISM, HOSTILITIES, CIVIL WAR, INSURRECTION, RIOT, CIVIL UNREST, COMMOTION OR ACTS OF A PUBLIC ENEMY; (C) LABOR SHORTAGES, STRIKES, LOCK-OUTS, OR OTHER LABOR, INDUSTRIAL OR TRADE ACTION, DISPUTES, DISRUPTION OR DISTURBANCES (WHETHER INVOLVING ITS EMPLOYEES OR THOSE OF ANY OTHER PERSON); (D) THEFT, SABOTAGE, MALICIOUS DAMAGE, FRAUD, EPIDEMIC, PANDEMIC, PLAGUES, OR QUARANTINE RESTRICTIONS; OR (E) FAILURE, MALFUNCTION OR UNAVAILABILITY OF POWER, TELECOMMUNICATIONS, DATA COMMUNICATIONS, OR RELATED SERVICES. ANY DELAY OR FAILURE OF THIS KIND WILL NOT BE DEEMED TO BE A BREACH OF THESE TERMS AND CONDITIONS AND LIMITED WARRANTY AND THE TIME FOR PERFORMANCE OF THE AFFECTED OBLIGATION WILL BE EXTENDED BY A PERIOD THAT IS REASONABLE IN THE CIRCUMSTANCES. A PARTY CLAIMING THE BENEFIT OF THIS CLAUSE WILL USE REASONABLE EFFORTS TO MITIGATE THE EFFECT OF ANY OF THE EVENTS OR CIRCUMSTANCES REFERRED TO ABOVE AND WILL PROMPTLY ADVISE THE OTHER PARTY OF THE DATE BY WHICH ITS PERFORMANCE MAY REASONABLY BE EXPECTED TO RESUME.<br />

<br />GOVERNING LAW/DISPUTE RESOLUTION/ARBITRATION<br />

<br />ALL MATTERS RELATING TO THE SITE AND TERMS AND ANY DISPUTE OR CLAIM ARISING THEREFROM OR RELATED THERETO (IN EACH CASE, INCLUDING NON-CONTRACTUAL DISPUTES OR CLAIMS), SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE INTERNAL LAWS OF THE STATE OF [CALIFORNIA] WITHOUT GIVING EFFECT TO ANY CHOICE OR CONFLICT OF LAW PROVISION OR RULE (WHETHER OF THE STATE OF [CALIFORNIA] OR ANY OTHER JURISDICTION).<br />

<br />BY USING THE SITE YOU AGREE THAT ANY DISPUTE, CLAIM OR CONTROVERSY ARISING OUT OF OR RELATING TO THESE TERMS OR THE BREACH, TERMINATION, ENFORCEMENT, INTERPRETATION OR VALIDITY THEREOF, INCLUDING THE DETERMINATION OF THE SCOPE OR APPLICABILITY OF THIS AGREEMENT TO ARBITRATE, SHALL BE DETERMINED BY ARBITRATION IN [LOS ANGELES, CALIFORNIA] BEFORE A SINGLE NEUTRAL ARBITRATOR. THE ARBITRATION SHALL BE ADMINISTERED BY JUDICIAL ARBITRATION AND MEDIATION SERVICES, INC. (“JAMS”) PURSUANT TO ITS COMPREHENSIVE ARBITRATION RULES AND PROCEDURES.  THE PARTIES TO ARBITRATION MAY USE LEGAL COUNSEL AT THEIR OWN EXPENSE. ALL COSTS OF ARBITRATION (INCLUDING ARBITRATOR FEES) SHALL BE PAID BY LATTER HOUSE, EXCEPT ONLY THAT IF YOU BRING THE ARBITRATION, YOU MAY BE CHARGED AN INITIAL FILING FEE THAT SHALL NOT EXCEED THE FILING FEES THAT YOU WOULD INCUR FOR BRINGING AN ACTION IN COURT.  WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, IN THE EVENT THAT ANY PARTY SEEKS INJUNCTIVE OR EQUITABLE RELIEF WITH RESPECT TO ANY ACTUAL OR THREATENED BREACH OF THESE TERMS, OR WITH RESPECT TO PUBLIC INJUNCTIVE RELIEF, SUCH PARTY MAY SEEK RELIEF IN A COURT OF COMPETENT JURISDICTION.  NOTWITHSTANDING ANYTHING ELSE IN THESE TERMS OR THE JAMS RULES, ANY PARTIES SUBJECT TO THIS ARBITRATION PROVISION SHALL BE BARRED FROM BRINGING OR PARTICIPATING IN ANY CLASS ACTION (AS DEFINED BELOW) RELATED TO A DISPUTE COVERED BY THIS ARBITRATION PROVISION. NOTWITHSTANDING ANYTHING ELSE IN THESE TERMS OR THE JAMS RULES, IT IS AGREED THAT THE ARBITRATOR IS SPECIFICALLY DENIED THE AUTHORITY TO CONSIDER OR CERTIFY ANY CLASS ACTION UNDER THESE TERMS.   HOWEVER, IF THESE CLASS ACTION RESTRICTIONS ARE EVER DEEMED ILLEGAL OR UNENFORCEABLE, THEY SHALL BE SEVERED FROM THIS ARBITRATION PROVISION. IN THAT EVENT, ANY CLASS ACTION SHALL BY EXEMPTED FROM THIS ARBITRATION PROVISION AND BROUGHT IN COURT OF COMPETENT JURISDICTION, IN CONNECTION THEREWITH AND EACH OF THE PARTIES CONSENT TO THE SOLE AND EXCLUSIVE JURISDICTION OF THE STATE AND FEDERAL COURTS OF THE STATE OF CALIFORNIA, COUNTY OF LOS ANGELES, CENTRAL DISTRICT. FOR PURPOSES OF THESE TERMS, THE TERM “CLASS ACTION” SHALL MEAN CLAIMS BROUGHT ON BEHALF OF OR ALLEGEDLY REPRESENTING OR INCLUDING OTHER PERSONS OR ENTITIES, INCLUDING BUT NOT LIMITED TO ANY CLASS, CONSOLIDATED, REPRESENTATIVE, COLLECTIVE OR PRIVATE ATTORNEY GENERAL ACTION. THIS ARBITRATION PROVISION IS SUBJECT TO THE FEDERAL ARBITRATION ACT, AND MAY BE ENFORCED IN ANY COURT OF COMPETENT JURISDICTION. <br />

<br />INFRINGEMENT<br />

<br />INFRINGEMENT NOTIFICATION. LATTER HOUSE RESPECTS THE RIGHTS OF OTHERS AND WE EXPECT USERS OF OUR SITE AND SERVICES TO DO THE SAME. THESE TERMS PROHIBIT THE INFRINGEMENT OF THE COPYRIGHTS OF OTHERS, AND IT IS ALSO OUR POLICY THAT WE MAY REMOVE, SUSPEND, TERMINATE ACCESS OF, OR TAKE OTHER APPROPRIATE ACTION AGAINST REPEAT OFFENDERS. WE MAY ALSO REMOVE CONTENT THAT IN OUR SOLE DISCRETION APPEARS TO INFRINGE THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS.
HOW TO FILE AN INFRINGEMENT NOTIFICATION. IF YOU HAVE EVIDENCE, KNOW, OR HAVE A GOOD FAITH BELIEF THAT CONTENT RESIDING ON OR ACCESSIBLE THROUGH OUR SITE INFRINGES A COPYRIGHT WHICH YOU OWN OR FOR WHICH YOU ARE A DESIGNATED AGENT, PLEASE SEND A NOTICE OF INFRINGEMENT BY FAX, ELECTRONIC MAIL OR REGULAR MAIL TO LATTER HOUSE’S DESIGNATED COPYRIGHT AGENT TO RECEIVE NOTIFICATIONS OF CLAIMED INFRINGEMENT BY ONE OF THE FOLLOWING MEANS:
LATTER HOUSE COPYRIGHT AGENT<br />

<br />ROBERT KLEINMAN
1112 RHINETTE AVENUE
BURLINGAME, CA 94010
512.299.5329
INFO@LATTER HOUSE.COM<br />

<br />WITH THE INFORMATION THAT SETS FORTH THE ITEMS SPECIFIED BELOW:<br />

<br />IDENTIFY THE COPYRIGHTED WORK CLAIMED TO HAVE BEEN INFRINGED. IF MULTIPLE COPYRIGHTED WORKS ARE COVERED BY A SINGLE NOTIFICATION, PROVIDE A REPRESENTATIVE LIST OF SUCH WORKS.
IDENTIFY THE MATERIAL THAT IS CLAIMED TO BE INFRINGING OR TO BE THE SUBJECT OF INFRINGING ACTIVITY. INCLUDE INFORMATION REASONABLY SUFFICIENT TO PERMIT LATTER HOUSE TO LOCATE THE MATERIAL. PLEASE PROVIDE A URL AND SCREENSHOTS FOR EACH ITEM. INCLUDE THE SPECIFIC ASSET(S) OR PAGE(S) THAT YOU CLAIM TO BE INFRINGING. SAY “ENTIRE WORK” ONLY IF ALL ASSETS/PAGES IN A COLLECTION/DOCUMENT ARE INFRINGING.
III.        INCLUDE DETAILS OF YOUR CLAIM TO THE MATERIAL, OR YOUR RELATIONSHIP TO THE MATERIAL’S COPYRIGHT HOLDER.<br />

<br />PROVIDE YOUR FULL NAME, ADDRESS, AND TELEPHONE NUMBER SHOULD WE NEED TO CLARIFY YOUR CLAIM.<br />
<br />PROVIDE A WORKING EMAIL ADDRESS WHERE WE CAN CONTACT YOU TO CONFIRM YOUR CLAIM.<br />
<br />IF TRUE, INCLUDE THE FOLLOWING STATEMENT: “I HAVE A GOOD FAITH BELIEF THAT USE OF THE COPYRIGHTED MATERIALS DESCRIBED ABOVE AS THE ALLEGEDLY INFRINGING WEB PAGES IS NOT AUTHORIZED BY THE COPYRIGHT OWNER, ITS AGENT, OR THE LAW.”<br />
<br />VII.       IF TRUE, INCLUDE THE FOLLOWING STATEMENT: “I SWEAR, UNDER PENALTY OF PERJURY, THAT THE INFORMATION IN THE NOTIFICATION IS ACCURATE AND THAT I AM THE COPYRIGHT OWNER OR AM AUTHORIZED TO ACT ON BEHALF OF THE COPYRIGHT OWNER TO MAKE THIS COMPLAINT.”<br />

<br />VIII.      SIGN THE DOCUMENT, PHYSICALLY OR ELECTRONICALLY.<br />

<br />MODIFICATIONS TO THESE TERMS.WE MAY MODIFY AND CHANGE THESE TERMS OVER TIME. WE WILL NOT "RETROACTIVELY" CHANGE THESE TERMS, AND ANY MODIFICATIONS WE MAKE SHALL TAKE EFFECT PROSPECTIVELY, ONCE YOU NEXT ACCESS THE WEBSITE. PLEASE FEEL FREE TO PRINT OUT A COPY OF THESE TERMS FOR YOUR RECORDS.<br />

<br />THESE TERMS SHALL NOT BE ASSIGNABLE BY YOU, EITHER IN WHOLE OR IN PART. LATTER HOUSE RESERVES THE RIGHT TO ASSIGN ITS RIGHTS AND OBLIGATIONS UNDER THESE TERMS.<br />

<br />IF ANY PROVISION OF THESE TERMS IS HELD TO BE INVALID OR UNENFORCEABLE, SUCH PROVISION SHALL BE STRUCK AND THE REMAINING PROVISIONS SHALL BE ENFORCED. HEADINGS ARE FOR REFERENCE PURPOSES ONLY AND IN NO WAY DEFINE, LIMIT, CONSTRUE, OR DESCRIBE THE SCOPE OR EXTENT OF SUCH SECTION. LATTER HOUSE’S FAILURE TO ACT WITH RESPECT TO A BREACH BY YOU OR OTHERS DOES NOT WAIVE ITS RIGHT TO ACT WITH RESPECT TO SUBSEQUENT OR SIMILAR BREACHES. THIS AGREEMENT AND THE TERMS AND CONDITIONS CONTAINED HEREIN SET FORTH THE ENTIRE UNDERSTANDING AND AGREEMENT BETWEEN LATTER HOUSE AND YOU WITH RESPECT TO THE SUBJECT MATTER HEREOF AND SUPERSEDE ANY PRIOR OR CONTEMPORANEOUS UNDERSTANDING, WHETHER WRITTEN OR ORAL.<br />

<br />ADDITIONAL TERMS.CERTAIN SERVICES MAY BE SUBJECT TO ADDITIONAL OR DIFFERENT TERMS AND CONDITIONS. WE WILL NOTIFY YOU IF THE SERVICE OR PORTION OF THE SITE IS SUBJECT TO TERMS AND CONDITIONS THAT DIFFER FROM THESE TERMS, AND YOU WILL HAVE THE OPPORTUNITY TO DECLINE TO PARTICIPATE IN SUCH SERVICE OR SITE IF YOU DO NOT AGREE WITH THE DIFFERING TERMS AND CONDITIONS.<br />

<br />IN ADDITION TO ANY PROVISION THAT BY ITS NATURE OR INTENT IS INTENDED TO SURVIVE THE TERMINATION OF THESE TERMS, THE FOLLOWING PROVISIONS SHALL SURVIVE THE TERMINATION OF THESE TERMS AND SHALL APPLY INDEFINITELY: (I)  (OWNERSHIP; RESERVATION OF RIGHTS); (II)  (WARRANTY DISCLAIMER); (III)  (LIMITATION OF LIABILITY); (IV)  (INDEMNITY); (V)  (ASSIGNMENT); AND (VI) (SURVIVAL).<br />

<br />RELATIONSHIP TO TERMS AND CONDITIONS, PRIVACY POLICY AND OTHER CONTRACTS.THESE TERMS MUST BE READ IN CONJUNCTION (I) WITH OTHER AGREEMENTS INTO WHICH YOU MAY ENTER CONCERNING THE WEBSITE (IF ANY), AND (II) WITH OUR PRIVACY POLICY AND TERMS AND CONDITIONS AND LIMITED WARRANTY. THE PROVISIONS OF OUR PRIVACY POLICY ARE INCORPORATED HEREIN. TO THE EXTENT THESE TERMS CONFLICT WITH THE TERMS OF OUR PRIVACY POLICY, THE TERMS OF OUR PRIVACY POLICY SHALL CONTROL. SIMILARLY, TO THE EXTENT THESE TERMS CONFLICT WITH THE TERMS AND CONDITIONS OF ANY SPECIFIC AGREEMENT YOU ENTER WITH US, THE TERMS AND CONDITIONS OF SUCH SPECIFIC AGREEMENT WILL CONTROL.<br />

<br />CONTACT US.IF YOU HAVE ANY QUESTIONS ABOUT THESE TERMS, THE PRACTICES OF THIS SITE, OR YOUR DEALINGS WITH THIS WEBSITE, PLEASE CONTACT US AT:<br />

<br />EMAIL: INFO@LATTERHOUSE.COM<br />

<br />EFFECTIVE DATE: THE EFFECTIVE DATE OF THESE TERMS OF USE IS JULY 6, 2021.<br />

<br />COPYRIGHT AND LEGAL NOTICE. COPYRIGHT LATTER HOUSE 2021. ALL RIGHTS RESERVED.<br />
          </p>
        </div>

        <div className={styles.home}>
        <Link style={{textDecoration: 'none', color: 'white'}} to="/">
          <UilHome />
        </Link>
      </div>
        
      </div>

      <Footer />
    </>
  )
}

export default Terms